### ISSUE TITLE
JSDoc Annotation in one row

### ISSUE THREAD

**Issue by Semigradsky** [davidderaedt/annotate-extension#11]
I press keyboard shortcut and received that:
![111](https://f.cloud.github.com/assets/1198848/1841776/ad1d2202-74ad-11e3-9e01-b6c43a060cdf.png)

Windows8, Brackets sprint 35 experimental build 0.35.0-10897 (release 445deaaa9)
I installed only "Annotate" and "Themes for Brackets" plugins.

**Comment by Semigradsky** [comment]
Problem repeated in current version.

**Comment by Hopiu** [comment]
Fixed in:
#22

**Comment by ShimShamSam** [comment]
@Hopiu Are you sure? I just downloaded the extension and still experience this bug
